### ISSUE TITLE
No output for nested types usage?

### ISSUE THREAD

**Issue by fser** [regit/coccigrep#19]
I wanted to use coccigrep on nginx's source code, so I've checked out https://github.com/nginx/nginx. The following experiments is done on master (as of today 65ae8b31).

In `src/http/ngx_http_variables.c` there is:

```
static ngx_int_t
ngx_http_variable_request_method(ngx_http_request_t *r,
    ngx_http_variable_value_t *v, uintptr_t data)
{
    if (r->main->method_name.data) {
        v->len = r->main->method_name.len;
        v->valid = 1;
        v->no_cacheable = 0;
        v->not_found = 0;
        v->data = r->main->method_name.data;

```

I wanted to track the use of `method_name`, defined in [ngx_http_request.h](https://github.com/nginx/nginx/blob/master/src/http/ngx_http_request.h#L413) in the `struct ngx_http_request_s` type.
As we can see, the `method_name` is accessed through the `main` field of type `ngx_http_request_t` ([source](https://github.com/nginx/nginx/blob/master/src/http/ngx_http_request.h#L418)) within the `struct ngx_http_request_s` type.

One last thing to know, is that `ngx_http_request_t` is an alias to `struct nginx_http_request_s` ([source](https://github.com/nginx/nginx/blob/master/src/http/ngx_http.h#L16)).

I was expecting `coccigrep -t  'ngx_http_request_t' -a method_name src/http/ngx_http_variables.c` to return several lines, as shown in the code snippet.

Also, `coccigrep -t ngx_http_request_t src/http/ngx_http_variables.c` returns results, whereas  `coccigrep -t  'struct ngx_http_request_s' src/http/` (or even the more specific `coccigrep -t  'struct ngx_http_request_s' src/http/ngx_http_variables.c src/http/ngx_http.h` which contains the file where the typedef is defined) doesn't yield any result.

Are those bugs, or expected behaviours? Thanks!

**Comment by regit** [comment]
This is tricky. I agree we could expect `coccigrep -t 'ngx_http_request_t' -a method_name src/http/ngx_http_variables.c` to match. I need to investigate.

**Comment by regit** [comment]
So we have:
```
$ coccigrep -t 'ngx_http_request_t' -a method_name src/http/ngx_http_variables.c -v
Running: spatch --recursive-includes -sp_file /tmp/tmpxkk322r1.cocci src/http/ngx_http_variables.c.
init_defs_builtins: /usr/local/bin/../lib/coccinelle/standard.h
HANDLING: src/http/ngx_http_variables.c
failed on ngx_config.h
failed on ngx_core.h
failed on ngx_http.h
failed on nginx.h
No match found in src/http/ngx_http_variables.c
```
And the SMPL file is:
```
// Author: Eric Leblond <eric@regit.org>
// Desc: Search for usage of a given attribute for a 'type' structure
// Confidence: 100%
// Arguments: type, attribute
// Revision: 1
@init@
ngx_http_request_t *p;
ngx_http_request_t ps;
position p1;
@@

(
p@p1->method_name
|
ps@p1.method_name
)

@ script:python @


p1 << init.p1;
@@

for p in p1:
    print("%s:%s:%s:%s:%s" % (p.file,p.line,p.column,p.line_end,p.column_end))
```

**Comment by regit** [comment]
We have a match with:
```
spatch --recursive-includes -sp_file /tmp/tmpxkk322r1.cocci src/http/ngx_http_variables.c   -I src/http/
```
Adding the include directory seems to fix the problem.

**Comment by regit** [comment]
Ah yes the include are absolute in `src/http/ngx_http_variables.c`

**Comment by regit** [comment]
I did try a fix here: https://github.com/regit/coccigrep/tree/include-fix

@fser can you try it ?

I'm not sure of the patch. I feel like automatically including the directory could lead to some problems. Need to think about it more.

**Comment by regit** [comment]
Fix pushed to master. Closing.

**Comment by fser** [comment]
Sorry I missed the notifications from github. I'll try this afternoon!
